- name: configure frontend service
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.bulitin.dnf:
      name: nginx
      state: latest
  - name: start and enable nginx
    ansible.bulitin.service:
      name: nginx
      state: started
      enabled: yes    